version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

jobs:
  test:
    docker:
      # Development and Production use Node v12.21
      # Using a Node base image
      # https://circleci.com/docs/2.0/circleci-images/#next-gen-language-images
      - image: cimg/node:12.21.0
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD

    steps:
      - checkout
      - restore_cache:
          # See the configuration reference documentation for more details on using restore_cache and save_cache steps
          # https://circleci.com/docs/2.0/configuration-reference/?section=reference#save_cache
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
      - run:
          name: install packages
          command: npm ci
      - save_cache:
          key: node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
          paths:
            - ~/.npm
      - run:
          name: Run linter
          command: npm run lint
      - run:
          name: Run Tests
          command: npm run test
      - codecov/upload:
          file: coverage/clover.xml

workflows:
  test:
    jobs:
      - test
